### ISSUE TITLE
Allow user to provide BindRule instance

### ISSUE THREAD

**Issue by autovalue** [manabreak/adapt#3]
It's currently not possible to bind to an ImageView using Picasso/Glide unless I expose them via a public static method and reference them from within `bind()`.

The library relies on the class having a no-args constructor, it would be much nicer if it allowed us to pass in the BindRule instance instead like this:
    
    picasso = daggerComponent.providePicasso();
    adapter.addType(R.layout.test_item, Test.class, new TestRule(picasso));

Here's an example of how my class was meant to be setup:
```java
public class TestRule extends BindRule<Test> {

    private final Picasso picasso;
    private TextView name;
    private ImageView thumb;

    public TestRule(Picasso picasso) {
        this.picasso = picasso;
    }

    @Override
    public void init() {
        name = find(R.id.name);
        thumb = find(R.id.thumbnail);
    }

    @Override
    public void bind(@NonNull Test test) {
        name.setText(test.name());
        picasso.load(test.image()).into(thumb);
    }
}
```

Allowing users to provide their own `BindRule` instance gives more flexibility regarding how the views are bound.

**Comment by autovalue** [comment]
I just found the `adapt.onItemBound` api which helps with this, nonetheless I think it'd make more sense for the image loading logic to be self contained within the the BindRule.

**Comment by manabreak** [comment]
By design, it would not make sense to provide an instance of the rule since the number of required rule instances varies - they're instantiated once per every view holder that requires them.

One solution would be to use reflection to provide constructor arguments. I've thought of implementing this myself, but the `onItemBound` callback has been sufficient for my needs for now.

You could also have a static provider for your Picasso instance, quite the same way the default instance works by calling `Picasso.with()`.

**Comment by autovalue** [comment]
I don't think using reflection to provide construction arguments is a good way to deal with this (it seems pretty hacky to me).

Given the way the library is designed, using `onItemBound` should be more than sufficient for now. I was merely curious if there was an easier way to go about it.

Thanks for all the feedback
